### ISSUE TITLE
Possible overcounts/undercounts, and AZ is missing from presidential precinct results

### ISSUE THREAD

**Issue by wtadler** [MEDSL/precinct-returns#2]
I did a little sanity check to make sure that the 2016 presidential votes, summed by state, add up to the official FEC totals. For the most part everything is almost perfect! Main issues are:

- KY is overcounted by about 20k votes
- NY is overcounted by about 35k votes
- OR is undercounted by about 10k votes
- AZ appears to be missing

[Here's](https://gist.github.com/wtadler/8e7939ef6e6e82ba5cc19dc89918548f) my analysis. I ran this on the dataverse data as well as the data downloaded from this repo!

**Comment by dwillis** [comment]
Interesting, @wtadler! I might note that FEC isn't the official repository for election results. The states are.

**Comment by wtadler** [comment]
Ah, I was wondering about that! Do you suspect that the states will have different totals? Is there a more trusted source that aggregates the official top-line counts so that I don't have to check each state individually?

**Comment by dwillis** [comment]
It's certainly possible that they will have different totals, since the FEC data is a snapshot of state-by-state results and there might be recounts or other certifications that have taken place to revise the numbers. In terms of a government source, it's the states.

**Comment by wtadler** [comment]
Okay, I'll try to check KY, NY, and OR at least.

**Comment by wtadler** [comment]
[KY's official results](https://elect.ky.gov/results/2010-2019/Documents/2016%20General%20Election%20Results.pdf), [NY's official results](https://www.elections.ny.gov/NYSBOE/elections/2016/General/2016President.xls), and [OR's official results](https://sos.oregon.gov/elections/Documents/results/november-2016-results.pdf) all exactly match the [FEC spreadsheet](https://transition.fec.gov/pubrec/fe2016/federalelections2016.xlsx) that I used above, so these do appear to be real overcounts/undercounts.

Do those states maybe account for absentee ballots, etc. in an unusual way?

**Comment by dwillis** [comment]
Hmm, I don't think so. If I had to guess, I might say that it could be something involving the presence of "Total" rows in the raw data that are getting double-counted.

**Comment by jamesdunham** [comment]
Thanks for contributing this, @wtadler. We'll be able to make two straightforward corrections in the next update:

* The AZ presidential returns were misfiled with the local results, but the precinct aggregates look good compared to the state canvass: -12 for Trump and -1 for Clinton.

* Tillamook County was excluded from the OR returns. Including it will add 6,538 votes for Trump and 5,768 for Clinton.

Resolving the overcounts in KY and NY will be a bit harder because the source data is messier. I'm going to open separate issues for these states.
