### ISSUE TITLE
Overcount in New York

### ISSUE THREAD

**Issue by jamesdunham** [MEDSL/precinct-returns#3]
Per #2 and @wtadler, there are too many votes for president in NY. Summing over precinct totals gives 4,572,604 for Clinton and 2,839,482 for Trump.  The [certified results (xls)](http://www.elections.ny.gov/NYSBOE/elections/2016/General/2016President.xls) show 4,379,783 and 2,527,141.

On inspection:

* The overcount is distributed across jurisdictions.
* Spot checks show the same in the [OE source data](https://github.com/openelections/openelections-data-ny), so we'll follow and resolve this upstream.
* The issue probably affects other races.

**Comment by dwillis** [comment]
I've begun looking at our source data and so far have found two counties where we have `total` rows included in the precinct files, which if not excluded would result in double-counting. I'm removing those rows from our files.

https://github.com/openelections/openelections-data-ny/issues/52
