### ISSUE TITLE
Some corrections

### ISSUE THREAD

**Issue by hobbes7878** [MEDSL/precinct-returns#7]
Hey there!

Over here at Politico, we're using your data to add context to our [race ratings](https://www.politico.com/election-results/2018/house-senate-race-ratings-and-predictions/). It's a great resource, but in the course of working with it, we found some errors and omissions.

Because we need to fix those changes as soon as we find them, we're deploying updates to our own repo, but we absolutely want to share those fixes to help improve the original dataset.

Here are the fixes we've made so far with links, one commit to each race we fixed:

- [CA-05, 2014](https://github.com/The-Politico/mit-elections-data/commit/c9faed5a489bc4709f0eb86e28c855135891c97f)
- [CA-17, 2016](https://github.com/The-Politico/mit-elections-data/commit/89fe7714bb5125f548e859e9ab886fba19beafc1)
- [WY-AL, 2016](https://github.com/The-Politico/mit-elections-data/commit/ba04bfae5192bd52cd0d7a6715c7a18a9ac2d0b1)
- [ND-AL, 2014](https://github.com/The-Politico/mit-elections-data/commit/8bc600211d271dd266104bf20ab7ada2d94de15b)
- [MS-04, 2012](https://github.com/The-Politico/mit-elections-data/commit/9b83809b654813f89c5fdb591e18c333fecb4729)
- [MS-03, 2012](https://github.com/The-Politico/mit-elections-data/commit/86c4cde28c67c8423062d637d1f148ae065803b8)
- [MS-02, 2012](https://github.com/The-Politico/mit-elections-data/commit/f5cfdf11a3c136fa3a7b47a9d009c8968c7c026d)
- [MS-01, 2012](https://github.com/The-Politico/mit-elections-data/commit/086325ff66b895ec304de1c8f7ba1a0fc3a4c1ea)
- [KS-04, 2012](https://github.com/The-Politico/mit-elections-data/commit/37f5ebe57920c36f3aacb6a1b6a19d17a2ed1187)
- [KS-03, 2012](https://github.com/The-Politico/mit-elections-data/commit/c2cbb504533ffef6af6f8447e8d66236ac8c1703)
- [KS-02, 2012](https://github.com/The-Politico/mit-elections-data/commit/3dbc856d2a1dc253194493efec1f1724b047aa2b)
- [KS-01, 2012](https://github.com/The-Politico/mit-elections-data/commit/baf914143085a8000eddbeb7c06ab80776287f3d)

We'd love to be able to continue submitting improvements to your data when we find mistakes. Submitting them piecemeal this way is OK, but while we're here we were wondering if you'd be at all interested in keeping this repo in a way that lets us more easily submit fixes like these through pull requests. The main change would be to keep the CSVs unzipped in the repo, which would let us simply fork and submit a PR for each fix.

Thanks again for compiling this data. Hope these corrections help!

**Comment by jamesdunham** [comment]
It's great to hear about how you're using the data. Thanks for taking the time to describe each of the corrections that you've made!

I see you're working with the [district-level House](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2) and [state-level presidential](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX) returns for 1976-2016. These older datasets have been hosted only on the [MEDSL Dataverse](https://dataverse.harvard.edu/dataverse/medsl_election_returns) so far, not in any of our repos. Let me create a new repo for them so we can more easily improve these datasets collaboratively, just as you say. I'll keep this issue open in the meantime. 

Thanks again.

**Comment by jamesdunham** [comment]
Ready [here](https://github.com/MEDSL/constituency-returns)!

**Comment by hobbes7878** [comment]
Fantastic, thanks!
